---
title: "Publications"
---

### __2020__

__Marchand LJ__, Dox I, Gričar J, Prislan P, van den Bulcke J, Fonti P, Campioli M (2020) [Timing of spring xylogenesis in temperate deciduous tree species relates to tree growth characteristics and previous autumn phenology](https://doi.org/10.1093/treephys/tpaa171). Tree Physiology, tpaa171, 


__Marchand LJ__, Tarayre M, Dorey T, Rantier Y, Hennion F (2020) [Morphological variability of cushion plant _Lyallia kerguelensis_ (Caryophyllales) in relation to environmental conditions and geography in the Kerguelen Islands: implications for cushion necrosis and climate change.](https://doi.org/10.1007/s00300-020-02768-2), Polar Biology


__Marchand LJ__, Dox I, Gričar J, Prislan P, Leys S, Van den Bulcke J, Fonti P, Lange H, Matthysen E, Peñuelas J, Zuccarini P, Campioli M (2020) [Inter-individual variability in spring phenology of temperate deciduous trees depends on species, tree size and previous year autumn phenology.](https://doi.org/10.1016/j.agrformet.2020.108031) Agricultural and Forest Meteorology 290:108031.


Dox I, Gričar J, __Marchand LJ__, Leys S, Zuccarini P, Geron C, Prislan P, Mariën B, Fonti P, Lange H, Peñuelas J, Van den Bulcke J, Campioli M (2020) [Timeline of autumn phenology in temperate deciduous trees](https://doi.org/10.1093/treephys/tpaa058). Tree Physiology 40:1001–1013.

### __2019__

Mariën B, Balzarolo M, Dox I, Leys S, __Marchand LJ__, Geron C, Portillo-Estrada M, AbdElgawad H, Asard H, Campioli M (2019) [Detecting the onset of autumn leaf senescence in deciduous forest trees of the temperate zone.](https://doi.org/10.1111/nph.15991) New Phytologist 224:166–176. 

