##  
##  
## __Talks__


## __2020__

__Marchand L.J.__, Tarayre M., Chambrin L., Verfaillie D., Favier V., Hennion F.. Necrosis dynamics, over time and space, of _Lyallia kerguelensis_ from individuals to population scale, CNFRA 2020, 22-23 September 2020, La Rochelle, France,

## __2019__

__Marchand L.J.__, Tarayre M., Dorey T., Rantier Y., Hennion F.. Morphological variability in relation to environmental conditions in the endemic cushion plant _Lyallia kerguelensis_ from Kerguelen Islands, GDR Plasphen 2019, 28-29 November 2019, Paris, France,


Cambiopli M. and __Marchand L.J.__   Inter-individual variability in spring phenology of late successional temperate deciduous trees is determined by tree growth characteristics and previous year autumn phenology. Eurodendro, 9-13th September  2019, Brno, Czech Republic:


## __Posters__ 

## __2021__

__Marchand L.J.__, F. Hennion, Tarayre M., M-C Martin, B. R. Martins, C. Monard. A specific Rhizomicrobiome selected by a long-lived endemic plant in the sub-Antartic Kerguelen Islans. World Microbe Forum, 20-24th June 2021, Online worldwide

## __2019__

Monard C., Martins B., __Marchand L.J.__, Tarayre M. and Hennion F. Diversité des communautés microbiennes de la  rhizosphère d’une plante endémique des îles. EFEM 2019, 5-8th November 2019, Bussang, France


